%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Hunter\Documents\HSRM\WISE20-21\Phys Praktikum 3\Versuche\4\matlab\noisy data\GLB.Ts+dSST.csv
%
% Auto-generated by MATLAB on 27-Jan-2021 16:23:31

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Year", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "JD", "DN", "DJF", "MAM", "JJA", "SON"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GLB = readtable("C:\Users\Hunter\Documents\HSRM\WISE20-21\Phys Praktikum 3\Versuche\4\matlab\noisy data\GLB.Ts+dSST.csv", opts);


%% Clear temporary variables
clear opts